// tslint:disable
/**
 * yhxk-api
 * Application related APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { FormStore, IFormField, FormType } from "common/FormStore";
import { Field } from "common/Field";
import * as _ from "lodash";
/**
 *
 * @export
 * @interface CorpUserVo
 */
export interface CorpUserVo {
  /**
   *
   * @type {number}
   * @memberof CorpUserVo
   */
  id?: number;
  /**
   * 用户名称
   * @type {string}
   * @memberof CorpUserVo
   */
  realName?: string;
  /**
   * 用户登录名
   * @type {string}
   * @memberof CorpUserVo
   */
  username?: string;
  /**
   * 用户手机号
   * @type {string}
   * @memberof CorpUserVo
   */
  mobile?: string;
  /**
   * 当前企业Code
   * @type {string}
   * @memberof CorpUserVo
   */
  currentCorpCode?: string;
  /**
   * 用户企业名称
   * @type {string}
   * @memberof CorpUserVo
   */
  currentCorpName?: string;
  /**
   * 企业类型
   * @type {number}
   * @memberof CorpUserVo
   */
  currentCorpType?: number;
  /**
   *
   * @type {number}
   * @memberof CorpUserVo
   */
  status?: CorpUserVoStatusEnum;
  /**
   *
   * @type {Array<number>}
   * @memberof CorpUserVo
   */
  roles?: Array<number>;
}

export function CorpUserVoFromJSON(json: any): CorpUserVo {
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    realName: !exists(json, "realName") ? undefined : json["realName"],
    username: !exists(json, "username") ? undefined : json["username"],
    mobile: !exists(json, "mobile") ? undefined : json["mobile"],
    currentCorpCode: !exists(json, "currentCorpCode") ? undefined : json["currentCorpCode"],
    currentCorpName: !exists(json, "currentCorpName") ? undefined : json["currentCorpName"],
    currentCorpType: !exists(json, "currentCorpType") ? undefined : json["currentCorpType"],
    status: !exists(json, "status") ? undefined : json["status"],
    roles: !exists(json, "roles") ? undefined : json["roles"],
  };
}

export function CorpUserVoToJSON(value?: CorpUserVo): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    id: value.id,
    realName: value.realName,
    username: value.username,
    mobile: value.mobile,
    currentCorpCode: value.currentCorpCode,
    currentCorpName: value.currentCorpName,
    currentCorpType: value.currentCorpType,
    status: value.status,
    roles: value.roles,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum CorpUserVoStatusEnum {
  NUMBER_1 = 1,
  NUMBER_2 = 2,
}

export type CorpUserVoFormKeys = keyof CorpUserVo;
export type CorpUserVoNewType = { [P in CorpUserVoFormKeys]: CorpUserVo[P] };
export type CorpUserVoFormType = FormType<CorpUserVoNewType>;

export function CorpUserVoFormDefault(): IFormField<CorpUserVo> {
  return {
    id: { value: void 0 },
    realName: { value: void 0 },
    username: { value: void 0 },
    mobile: { value: void 0 },
    currentCorpCode: { value: void 0 },
    currentCorpName: { value: void 0 },
    currentCorpType: { value: void 0 },
    status: { value: void 0 },
    roles: { value: void 0 },
  } as any;
}

export function createCorpUserVoFormStore<T>(field?: IFormField<T>): CorpUserVoFormType & FormType<T> {
  const fields: IFormField<T & CorpUserVo> = _.merge<any, any>(CorpUserVoFormDefault(), field);
  return new FormStore(_.mapValues<IFormField<T & CorpUserVo>, Field<any>>(fields, (item: any) => {
    if (typeof item!!.rules !== "undefined") {
      return new Field(item).validators(...item.rules);
    }
    return new Field(item);
  }) as any);
}
