// tslint:disable
/**
 * yhxk-api
 * Application related APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CorpUserResourceDto
 */
export interface CorpUserResourceDto {
  /**
   *
   * @type {number}
   * @memberof CorpUserResourceDto
   */
  userId?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof CorpUserResourceDto
   */
  resourceIds?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof CorpUserResourceDto
   */
  roles?: Array<number>;
}

export function CorpUserResourceDtoFromJSON(json: any): CorpUserResourceDto {
  return {
    userId: !exists(json, "userId") ? undefined : json["userId"],
    resourceIds: !exists(json, "resourceIds") ? undefined : json["resourceIds"],
    roles: !exists(json, "roles") ? undefined : json["roles"],
  };
}

export function CorpUserResourceDtoToJSON(value?: CorpUserResourceDto): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    userId: value.userId,
    resourceIds: value.resourceIds,
    roles: value.roles,
  };
}
