// tslint:disable
/**
 * yhxk-api
 * Application related APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SysParamVo
 */
export interface SysParamVo {
  /**
   * 参数查询key值
   * @type {string}
   * @memberof SysParamVo
   */
  pkey?: string;
  /**
   * 参数值
   * @type {string}
   * @memberof SysParamVo
   */
  pvalue?: string;
  /**
   * 参数显示值
   * @type {string}
   * @memberof SysParamVo
   */
  pdesc?: string;
  /**
   * 参数父级值
   * @type {string}
   * @memberof SysParamVo
   */
  ppvalue?: string;
}

export function SysParamVoFromJSON(json: any): SysParamVo {
  return {
    pkey: !exists(json, "pkey") ? undefined : json["pkey"],
    pvalue: !exists(json, "pvalue") ? undefined : json["pvalue"],
    pdesc: !exists(json, "pdesc") ? undefined : json["pdesc"],
    ppvalue: !exists(json, "ppvalue") ? undefined : json["ppvalue"],
  };
}

export function SysParamVoToJSON(value?: SysParamVo): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    pkey: value.pkey,
    pvalue: value.pvalue,
    pdesc: value.pdesc,
    ppvalue: value.ppvalue,
  };
}
