// tslint:disable
/**
 * yhxk-api
 * Application related APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { PermissionVo, PermissionVoFromJSON, PermissionVoToJSON } from "./";

/**
 *
 * @export
 * @interface UserDetailVo
 */
export interface UserDetailVo {
  /**
   *
   * @type {string}
   * @memberof UserDetailVo
   */
  currentCorpCode?: string;
  /**
   *
   * @type {number}
   * @memberof UserDetailVo
   */
  currentCorpId?: number;
  /**
   *
   * @type {string}
   * @memberof UserDetailVo
   */
  currentCorpName?: string;
  /**
   * 企业类型，1.平台方,2供应链企业,3保理商,4资金方,5保证方,6核心企业,7成员企业
   * @type {number}
   * @memberof UserDetailVo
   */
  currentCorpType?: number;
  /**
   * 企业状态，1未认证,2待审核,3有效,4审核未通过,5无效,6冻结
   * @type {number}
   * @memberof UserDetailVo
   */
  currentCorpStatus?: number;
  /**
   *
   * @type {number}
   * @memberof UserDetailVo
   */
  id?: number;
  /**
   *
   * @type {Array<PermissionVo>}
   * @memberof UserDetailVo
   */
  permissions?: Array<PermissionVo>;
  /**
   *
   * @type {string}
   * @memberof UserDetailVo
   */
  phone?: string;
  /**
   *
   * @type {string}
   * @memberof UserDetailVo
   */
  realName?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof UserDetailVo
   */
  roles?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof UserDetailVo
   */
  username?: string;
  /**
   * 1正常，2需要重置密码
   * @type {number}
   * @memberof UserDetailVo
   */
  pwdStatus?: number;
}

export function UserDetailVoFromJSON(json: any): UserDetailVo {
  return {
    currentCorpCode: !exists(json, "currentCorpCode") ? undefined : json["currentCorpCode"],
    currentCorpId: !exists(json, "currentCorpId") ? undefined : json["currentCorpId"],
    currentCorpName: !exists(json, "currentCorpName") ? undefined : json["currentCorpName"],
    currentCorpType: !exists(json, "currentCorpType") ? undefined : json["currentCorpType"],
    currentCorpStatus: !exists(json, "currentCorpStatus") ? undefined : json["currentCorpStatus"],
    id: !exists(json, "id") ? undefined : json["id"],
    permissions: !exists(json, "permissions")
      ? undefined
      : (json["permissions"] as Array<any>).map(PermissionVoFromJSON),
    phone: !exists(json, "phone") ? undefined : json["phone"],
    realName: !exists(json, "realName") ? undefined : json["realName"],
    roles: !exists(json, "roles") ? undefined : json["roles"],
    username: !exists(json, "username") ? undefined : json["username"],
    pwdStatus: !exists(json, "pwdStatus") ? undefined : json["pwdStatus"],
  };
}

export function UserDetailVoToJSON(value?: UserDetailVo): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    currentCorpCode: value.currentCorpCode,
    currentCorpId: value.currentCorpId,
    currentCorpName: value.currentCorpName,
    currentCorpType: value.currentCorpType,
    currentCorpStatus: value.currentCorpStatus,
    id: value.id,
    permissions:
      value.permissions === undefined ? undefined : (value.permissions as Array<any>).map(PermissionVoToJSON),
    phone: value.phone,
    realName: value.realName,
    roles: value.roles,
    username: value.username,
    pwdStatus: value.pwdStatus,
  };
}
