swagger: "2.0"
info:
  version: "1.0.0"
  title: "es-cash-flow-api"
host: "harry.shaw.com"
schemes:
  - "http"
  - "https"
basePath: "/"
produces:
  - "application/json"
tags:
  - name: "cashFlow"
    description: "cash flow related APIs"

paths:
  /cash/record:
    post:
      tags:
        - "cashFlow"
      summary: "资金明细添加"
      operationId: "createCashRecord"
      parameters:
        - in: "body"
          name: "cashRecord"
          required: true
          schema:
            $ref: "#/definitions/CashRecord"
      responses:
        200:
          description: "response ok"
          schema:
            type: "integer"
            format: "int64"

definitions:
  CashRecord:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "明细id"
      direction:
        type: "integer"
        format: "int32"
        description: "现金流向类别，1:支出 2:收入"
      accountId:
        type: "integer"
        format: "int64"
        description: "账户id"
      tag:
        type: "integer"
        format: "int64"
        description: "类别id"
      amount:
        type: "number"
        description: "金额"
      cashDate:
        type: "string"
        format: "date-time"
        description: "费用发生日期"
      remark:
        type: "string"
        description: "备注"
