swagger: '2.0'
definitions:
  SuccessResponseVo:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"

  ErrorResponseVo:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"

  QueryPageVo:
    type: object
    properties:
      pageNum:
        type: "integer"
        format: "int32"
        description: "分页单位"
      pageSize:
        type: "integer"
        format: "int32"
        description: "分页页码"


  BusinessEntityVo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "业务实体id"
      name:
        type: "string"
        description: "业务实体名称"

  BankAccountVo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "银行账号id"
      payeeName:
        type: "string"
        description: "收款人姓名"
      bankName:
        type: "string"
        description: "银行名称"
      bankBranchName:
        type: "string"
        description: "支行名称"
      bankAccountNo:
        type: "string"
        description: "银行卡号"
      cnap:
        type: "string"
        description: "开户网点联行号"

  AttachmentVo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "附件Id"
      name:
        type: "string"
        description: "附件名称"
      url:
        type: "string"
        description: "附件地址"
      type:
        type: "string"
        description: "附件文件类型，doc,pdf,ppt,xls,xlsx等"

  ApprovalHistoryVo:
    type: "object"
    properties:
      approverName:
        type: "string"
        description: "审批人姓名"
      approverJobPost:
        type: "string"
        description: "审批人职务名称"
      approverDepartment:
        type: "string"
        description: "审批人所属部门名称"
      approvalTime:
        type: "string"
        format: "date-time"
        description: "审批时间"
      approvalResult:
        type: "string"
        description: "审批结果"
      approvalComment:
        type: "string"
        description: "审批意见"

  BacklogVo:
    type: "object"
    properties:
      formId:
        type: "integer"
        format: "int64"
        description: "报销单id"
      templateType:
        type: "integer"
        format: "int32"
        description: "模板类型，用来表示是报销单，申请单还是借款单"
      templateId:
        type: "integer"
        format: "int64"
        description: "模板id"
      templateName:
        type: "string"
        description: "模板名称"
      formName:
        type: "string"
        description: "单据名称"
      status:
        type: "integer"
        format: "int32"
        description: "单据审批状态"
      employeeName:
        type: "string"
        description: "申请人姓名"
      createdTime:
        type: "string"
        format: "date-time"
        description: "单据创建时间"
      amount:
        type: "number"
        description: "金额"
      latestApprovalLog:
        $ref: '#/definitions/ApprovalHistoryVo'

  QueryMyFormPageReqVo:
    type: "object"
    properties:
      pageNum:
        type: "integer"
        format: "int32"
        description: "pageNum 当前页"
      pageSize:
        type: "integer"
        format: "int32"
        description: "pageSize 每页条数"

  CommonFormDetailVo:
    type: "object"
    properties:
      templateId:
        type: "integer"
        format: "int64"
        description: "模板id"
      formId:
        type: "integer"
        format: "int64"
        description: "单据id"
      templateName:
        type: "string"
        description: "申请单模板名称"
      applicantId:
        type: "integer"
        format: "int64"
        description: "申请人Id"
      applicantName:
        type: "string"
        description: "申请人名称"
      applicantDeptId:
        type: "integer"
        format: "int64"
        description: "部门Id"
      applicantDeptName:
        type: "string"
        description: "部门名称"
      formName:
        type: "string"
        description: "事由"
      templateType:
        type: "integer"
        format: "int32"
        description: "表单模板类型"
      approver:
        type: "array"
        items:
          type: "string"
          description: "下一个审批人+status"
      status:
        type: "integer"
        format: "int32"
        description: "表单状态"
      amount:
        type: "number"
        description: "金额"
      createdTime:
        type: "string"
        format: "date-time"

  FormDataVo:
    type: "object"
    properties:
      elementId:
        type: "integer"
        format: "int64"
        description: "字段id"
      elementName:
        type: "string"
        description: "字段名称"
      elementCode:
        type: "string"
        description: "字段编号"
      elementValue:
         type: "string"
         description: "字段内容id"
      elementContent:
         type: "string"
         description: "字段内容"

  FormDataVo:
    type: "object"
    properties:
      elementId:
        type: "integer"
        format: "int64"
        description: "字段id"
      elementName:
        type: "string"
        description: "字段名称"
      elementCode:
        type: "string"
        description: "字段编号"
      elementValue:
         type: "string"
         description: "字段内容id"
      elementContent:
         type: "string"
         description: "字段内容"

  ReimDeductionVo:
    type: "object"
    properties:
      formId:
        type: "integer"
        format: "int64"
        description: "表单Id"
      templateType:
        type: "integer"
        format: "int64"
        description: "表单类型"
      formName:
        type: "string"
        description: "表单名称"
      amount:
        type: "number"
        description: "核销金额"
      formSn:
        type: "string"
        description: "申请单单号"
  FormElementForUser:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "元素id"
      elementCode:
        type: "string"
        description: "元素在表单提交时的key"
      elementName:
        type: "string"
        description: "元素显示名称"
      elementEnglishName:
        type: "string"
        description: "元素显示英文名称"  
      isDefault:
        type: "boolean"
        description: "元素是否为系统指定必填项"
      elementType:
        type: "string"
        description: "元素类型"
      elementFormat:
        type: "string"
        description: "显示类型"
      filterEnumValue:
        type: "string"
        description: "元素对应的枚举型数据值多个用,分割"  
      isRequired:
        type: "boolean"
        description: "是否必填"
      indexNo:
        type: "integer"  
        description: "排序"
      isEdit:
        type: "boolean"
        description: "审批人是否可以修改"  
      elementValue:
        type: "string"
        description: "字段内容id"
      elementContent:
        type: "string"
        description: "字段内容"   

  ApprovalApplicationFormVo:
    type: "object"
    properties:
      templateId:
        type: "integer"
        format: "int64"
        description: "选择的模板id"
      formDataList:
        type: "array"
        items:
          $ref: './ApplicationApi.yaml#/definitions/ApplicationFormDataVo'
      attachmentIdList:
        type: "array"
        items:
          type: "integer"
          format: "int64"
        description: "附件id集合"
      selectApproveList:
        type: "array"
        items:
          $ref: '#/definitions/SelectApproveVo'
      ccList:
        type: "array"
        items:
          $ref: '#/definitions/CarbonCopyTo' 
  ApprovalLoanFormVo:
    type: "object"
    properties:
      templateId:
        type: "integer"
        format: "int64"
        description: "选择的模板id"
      formDataList:
        type: "array"
        items:
          $ref: './LoanFormServiceApi.yaml#/definitions/FormDataVo'
      attachmentIdList:
        type: "array"
        items:
          type: "integer"
          format: "int64"
        description: "附件id集合"
      selectApproveList:
        type: "array"
        items:
          $ref: '#/definitions/SelectApproveVo'
      ccList:
        type: "array"
        description: "抄送人列表"
        items:
          $ref: '#/definitions/CarbonCopyTo' 
  ApprovalReimFormVo:
    type: "object"
    properties:
      formId:
        type: "integer"
        format: "int64"
        description: "单据Id"
      templateId:
        type: "integer"
        format: "int64"
        description: "选择的模板id"
      formDataList:
        type: "array"
        items:
          $ref: './ReimbursementApi.yaml#/definitions/ReimFormDataVo'
      expenseRecordIdList:
        type: "array"
        items:
          type: "integer"
          format: "int64"
      selectApproveList:
        type: "array"
        items:
          $ref: '#/definitions/SelectApproveVo'
      ccList:
        type: "array"
        items:
          $ref: "#/definitions/CarbonCopyTo"                  
  SelectApproveVo:
    type: "object"
    properties:
      nodeId:
        type: "integer"
        format: "int64"
        description: "节点Id"
      ApproveId:
        type: "integer"
        format: "int64"
        description: "选择的审批人ID"           
  CarbonCopyTo:
    type: "object"
    description: "抄送人"
    properties:
      employeeId:
        type: "integer"
        format: "int64"
        description: "抄送人id"
      employeeName:
        type: "string"
        description: "抄送人姓名"
      preDefined:
        type: "boolean"
        description: "是否为默认抄送人"

