/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * es-cash-flow-api
 * cash flow related APIs of Xinhehui Enterprise Service Expense System. 建立鑫合汇企业财务账本相关API。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://expense-test1.xinhehui.com".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface AssetsAccountDailyFlowPagingVo
 */
export interface AssetsAccountDailyFlowPagingVo {
    /**
     * 剩余流水条数
     * @type {number}
     * @memberof AssetsAccountDailyFlowPagingVo
     */
    remainQty?: any;
    /**
     * 
     * @type {Array<DailyCashFlowVo>}
     * @memberof AssetsAccountDailyFlowPagingVo
     */
    dailyCashFlowList?: any;
}

/**
 * 
 * @export
 * @interface AssetsAccountDailyFlowQueryVo
 */
export interface AssetsAccountDailyFlowQueryVo {
    /**
     * 每页条数
     * @type {number}
     * @memberof AssetsAccountDailyFlowQueryVo
     */
    pageSize?: any;
    /**
     * 上一次查询结果的最后一条数据
     * @type {CashRecordDetail}
     * @memberof AssetsAccountDailyFlowQueryVo
     */
    lastRecord?: any;
}

/**
 * 
 * @export
 * @interface AssetsAccountOverviewVo
 */
export interface AssetsAccountOverviewVo {
    /**
     * 账户Id
     * @type {number}
     * @memberof AssetsAccountOverviewVo
     */
    accountId?: any;
    /**
     * 账户名称
     * @type {string}
     * @memberof AssetsAccountOverviewVo
     */
    accountName?: any;
    /**
     * 账户余额
     * @type {number}
     * @memberof AssetsAccountOverviewVo
     */
    balance?: any;
    /**
     * 账户流入金额，从最新一次的余额变动开始计算
     * @type {number}
     * @memberof AssetsAccountOverviewVo
     */
    incomeAmount?: any;
    /**
     * 账户流入金额，从最新一次的余额变动开始计算
     * @type {number}
     * @memberof AssetsAccountOverviewVo
     */
    outcomeAmount?: any;
    /**
     * 剩余流水条数
     * @type {number}
     * @memberof AssetsAccountOverviewVo
     */
    remainQty?: any;
    /**
     * 部分的账户流水，大小由pageSize决定
     * @type {Array<CashAccountVo>}
     * @memberof AssetsAccountOverviewVo
     */
    dailyCashFlowList?: any;
}

/**
 * 
 * @export
 * @interface AssetsManagerOverviewVo
 */
export interface AssetsManagerOverviewVo {
    /**
     * 净资产
     * @type {number}
     * @memberof AssetsManagerOverviewVo
     */
    netAssetsAmount?: any;
    /**
     * 总资产
     * @type {number}
     * @memberof AssetsManagerOverviewVo
     */
    totalAssetsAmount?: any;
    /**
     * 总负债
     * @type {number}
     * @memberof AssetsManagerOverviewVo
     */
    totalDebtAmount?: any;
    /**
     * 账户类型分组信息
     * @type {Array<CashAccountGroupVo>}
     * @memberof AssetsManagerOverviewVo
     */
    accountGroup?: any;
}

/**
 * 
 * @export
 * @interface CashAccountGroupVo
 */
export interface CashAccountGroupVo {
    /**
     * 账户类型 0 现金、1 虚拟卡/借记卡、2 虚拟账户
     * @type {number}
     * @memberof CashAccountGroupVo
     */
    type?: any;
    /**
     * 账户类型名称
     * @type {string}
     * @memberof CashAccountGroupVo
     */
    name?: any;
    /**
     * 排序的顺序
     * @type {number}
     * @memberof CashAccountGroupVo
     */
    order?: any;
    /**
     * 净资产金额
     * @type {number}
     * @memberof CashAccountGroupVo
     */
    netBalance?: any;
    /**
     * 改账户类型下所有的账户
     * @type {Array<CashAccountVo>}
     * @memberof CashAccountGroupVo
     */
    accountList?: any;
}

/**
 * 
 * @export
 * @interface CashAccountVo
 */
export interface CashAccountVo {
    /**
     * 账户Id
     * @type {number}
     * @memberof CashAccountVo
     */
    id?: any;
    /**
     * 账户类型 0 现金、1 虚拟卡/借记卡、2 虚拟账户
     * @type {number}
     * @memberof CashAccountVo
     */
    payType?: any;
    /**
     * 账户名
     * @type {string}
     * @memberof CashAccountVo
     */
    accountName?: any;
    /**
     * 账户余额
     * @type {number}
     * @memberof CashAccountVo
     */
    accountAmount?: any;
    /**
     * 银行Id
     * @type {number}
     * @memberof CashAccountVo
     */
    bankId?: any;
    /**
     * 银行名称
     * @type {string}
     * @memberof CashAccountVo
     */
    bankName?: any;
    /**
     * 银行图标
     * @type {string}
     * @memberof CashAccountVo
     */
    bankFigure?: any;
    /**
     * 支行Id
     * @type {number}
     * @memberof CashAccountVo
     */
    bankBranchId?: any;
    /**
     * 支行名称
     * @type {string}
     * @memberof CashAccountVo
     */
    bankBranchName?: any;
    /**
     * 支行联行号
     * @type {string}
     * @memberof CashAccountVo
     */
    bankBranchCnaps?: any;
    /**
     * 银行卡号
     * @type {string}
     * @memberof CashAccountVo
     */
    bankNo?: any;
    /**
     * 省份代码
     * @type {string}
     * @memberof CashAccountVo
     */
    provinceCode?: any;
    /**
     * 省份名称
     * @type {string}
     * @memberof CashAccountVo
     */
    provinceName?: any;
    /**
     * 城市代码
     * @type {string}
     * @memberof CashAccountVo
     */
    cityCode?: any;
    /**
     * 城市名称
     * @type {string}
     * @memberof CashAccountVo
     */
    cityName?: any;
    /**
     * 是否计入净资产
     * @type {boolean}
     * @memberof CashAccountVo
     */
    allowNetAsset?: any;
    /**
     * 备注
     * @type {string}
     * @memberof CashAccountVo
     */
    remark?: any;
}

/**
 * 
 * @export
 * @interface CashMonthListVo
 */
export interface CashMonthListVo {
    /**
     * 是否结束 0否1是
     * @type {number}
     * @memberof CashMonthListVo
     */
    totalEnd?: any;
    /**
     * 
     * @type {Array<CashMonthVo>}
     * @memberof CashMonthListVo
     */
    list?: any;
}

/**
 * 
 * @export
 * @interface CashMonthQueryVo
 */
export interface CashMonthQueryVo {
    /**
     * 查询年月
     * @type {Date}
     * @memberof CashMonthQueryVo
     */
    startDate?: any;
    /**
     * 查询条数，默认24条
     * @type {number}
     * @memberof CashMonthQueryVo
     */
    pageSize?: any;
}

/**
 * 
 * @export
 * @interface CashMonthVo
 */
export interface CashMonthVo {
    /**
     * 年月的时间戳
     * @type {number}
     * @memberof CashMonthVo
     */
    month?: any;
    /**
     * 月收入金额
     * @type {number}
     * @memberof CashMonthVo
     */
    debitAmount?: any;
    /**
     * 月支出金额
     * @type {number}
     * @memberof CashMonthVo
     */
    creditAmount?: any;
    /**
     * 月结余：等于【收】减去【支】金额
     * @type {number}
     * @memberof CashMonthVo
     */
    cashSurplus?: any;
}

/**
 * 
 * @export
 * @interface CashParam
 */
export interface CashParam {
    /**
     * 
     * @type {number}
     * @memberof CashParam
     */
    id?: any;
    /**
     * 参数类型 单元 1，tag(分类) 2
     * @type {number}
     * @memberof CashParam
     */
    paramType?: any;
    /**
     * 值
     * @type {string}
     * @memberof CashParam
     */
    paramValue?: any;
    /**
     * 分类是否常用 0 否 1是
     * @type {number}
     * @memberof CashParam
     */
    starTarget?: any;
}

/**
 * 
 * @export
 * @interface CashRecord
 */
export interface CashRecord {
    /**
     * 明细id
     * @type {number}
     * @memberof CashRecord
     */
    id?: any;
    /**
     * 现金流向类别，1:支出 2:收入
     * @type {number}
     * @memberof CashRecord
     */
    direction?: any;
    /**
     * 账户id
     * @type {number}
     * @memberof CashRecord
     */
    accountId?: any;
    /**
     * 类别id
     * @type {number}
     * @memberof CashRecord
     */
    tag?: any;
    /**
     * 金额
     * @type {number}
     * @memberof CashRecord
     */
    amount?: any;
    /**
     * 费用发生日期
     * @type {Date}
     * @memberof CashRecord
     */
    cashDate?: any;
    /**
     * 备注
     * @type {string}
     * @memberof CashRecord
     */
    remark?: any;
    /**
     * 归属单元
     * @type {CashUnit}
     * @memberof CashRecord
     */
    unit?: any;
}

/**
 * 
 * @export
 * @interface CashRecordDayVo
 */
export interface CashRecordDayVo {
    /**
     * 发生日期时间戳
     * @type {number}
     * @memberof CashRecordDayVo
     */
    cashTimestamp?: any;
    /**
     * 当天收入金额
     * @type {number}
     * @memberof CashRecordDayVo
     */
    debitAmount?: any;
    /**
     * 当天支出金额
     * @type {number}
     * @memberof CashRecordDayVo
     */
    creditAmount?: any;
    /**
     * 
     * @type {Array<CashRecordDetail>}
     * @memberof CashRecordDayVo
     */
    recordList?: any;
}

/**
 * 
 * @export
 * @interface CashRecordDetail
 */
export interface CashRecordDetail {
    /**
     * 明细id
     * @type {number}
     * @memberof CashRecordDetail
     */
    id?: any;
    /**
     * 现金流向类别，1:支出 2:收入
     * @type {number}
     * @memberof CashRecordDetail
     */
    direction?: any;
    /**
     * 账户id
     * @type {number}
     * @memberof CashRecordDetail
     */
    accountId?: any;
    /**
     * 账户名
     * @type {string}
     * @memberof CashRecordDetail
     */
    accountName?: any;
    /**
     * 类别id
     * @type {number}
     * @memberof CashRecordDetail
     */
    tag?: any;
    /**
     * 类别值
     * @type {string}
     * @memberof CashRecordDetail
     */
    tagName?: any;
    /**
     * 账户余额
     * @type {number}
     * @memberof CashRecordDetail
     */
    accountAmount?: any;
    /**
     * 金额
     * @type {number}
     * @memberof CashRecordDetail
     */
    amount?: any;
    /**
     * 费用发生日期
     * @type {Date}
     * @memberof CashRecordDetail
     */
    cashDate?: any;
    /**
     * 备注
     * @type {string}
     * @memberof CashRecordDetail
     */
    remark?: any;
    /**
     * 归属单元
     * @type {CashUnit}
     * @memberof CashRecordDetail
     */
    unit?: any;
    /**
     * 该条流水产生后的账户余额
     * @type {number}
     * @memberof CashRecordDetail
     */
    balance?: any;
    /**
     * 流水排序用的Id
     * @type {number}
     * @memberof CashRecordDetail
     */
    seqId?: any;
}

/**
 * 
 * @export
 * @interface CashRecordQueryVo
 */
export interface CashRecordQueryVo {
    /**
     * 分页单位
     * @type {number}
     * @memberof CashRecordQueryVo
     */
    pageNum?: any;
    /**
     * 分页页码
     * @type {number}
     * @memberof CashRecordQueryVo
     */
    pageSize?: any;
    /**
     * 费用发生日期开始时间
     * @type {Date}
     * @memberof CashRecordQueryVo
     */
    startTime?: any;
    /**
     * 费用发生日期结束时间
     * @type {Date}
     * @memberof CashRecordQueryVo
     */
    endTime?: any;
    /**
     * 现金流向类别，1:支出 2:收入
     * @type {number}
     * @memberof CashRecordQueryVo
     */
    direction?: any;
    /**
     * 关键字
     * @type {string}
     * @memberof CashRecordQueryVo
     */
    keyword?: any;
    /**
     * 起始金额
     * @type {number}
     * @memberof CashRecordQueryVo
     */
    startAmount?: any;
    /**
     * 终止金额
     * @type {number}
     * @memberof CashRecordQueryVo
     */
    endAmount?: any;
    /**
     * 账户ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    accountIds?: any;
    /**
     * 分类ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    tags?: any;
    /**
     * 部门单元ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    deptIds?: any;
    /**
     * 员工ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    employeeIds?: any;
    /**
     * 项目ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    projectIds?: any;
    /**
     * 自定义ids
     * @type {Array<number>}
     * @memberof CashRecordQueryVo
     */
    userDefineds?: any;
}

/**
 * 
 * @export
 * @interface CashUnit
 */
export interface CashUnit {
    /**
     * 部门id
     * @type {number}
     * @memberof CashUnit
     */
    deptId?: any;
    /**
     * 部门名称
     * @type {string}
     * @memberof CashUnit
     */
    deptName?: any;
    /**
     * 人员id
     * @type {number}
     * @memberof CashUnit
     */
    employeeId?: any;
    /**
     * 员工名称
     * @type {string}
     * @memberof CashUnit
     */
    employeeName?: any;
    /**
     * 项目id
     * @type {number}
     * @memberof CashUnit
     */
    projectId?: any;
    /**
     * 项目名称
     * @type {string}
     * @memberof CashUnit
     */
    projectName?: any;
    /**
     * 自定义id
     * @type {number}
     * @memberof CashUnit
     */
    userDefined?: any;
    /**
     * 自定义值
     * @type {string}
     * @memberof CashUnit
     */
    userDefinedValue?: any;
}

/**
 * 
 * @export
 * @interface DailyCashFlowVo
 */
export interface DailyCashFlowVo {
    /**
     * 以天为单位的流水发生日期的时间戳
     * @type {number}
     * @memberof DailyCashFlowVo
     */
    cashTimestamp?: any;
    /**
     * 每天账户的资金净值，每日净值 = 每日收入明细总额 - 每日支出明细总额
     * @type {number}
     * @memberof DailyCashFlowVo
     */
    balance?: any;
    /**
     * 
     * @type {Array<CashRecordDetail>}
     * @memberof DailyCashFlowVo
     */
    cashFlowList?: any;
}

/**
 * 
 * @export
 * @interface ErrorResponseVo
 */
export interface ErrorResponseVo {
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseVo
     */
    status?: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseVo
     */
    message?: any;
}

/**
 * 
 * @export
 * @interface ExcelImportResultVo
 */
export interface ExcelImportResultVo {
    /**
     * 是否导入成功
     * @type {boolean}
     * @memberof ExcelImportResultVo
     */
    success?: any;
    /**
     * 错误类型，1模板错误，2数据错误
     * @type {string}
     * @memberof ExcelImportResultVo
     */
    errorType?: any;
    /**
     * 总的错误信息，例如‘模板错误’
     * @type {string}
     * @memberof ExcelImportResultVo
     */
    errorMessage?: any;
    /**
     * company scope id 公司规模ID
     * @type {Array<string>}
     * @memberof ExcelImportResultVo
     */
    errorDataMessages?: any;
    /**
     * 导入的数据行数
     * @type {number}
     * @memberof ExcelImportResultVo
     */
    totalRecord?: any;
    /**
     * 错误的数据行数
     * @type {number}
     * @memberof ExcelImportResultVo
     */
    errorRecord?: any;
}


/**
 * CashFlowApi - fetch parameter creator
 * @export
 */
export const CashFlowApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 查询指定年月的资金明细汇总
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateDetail(queryVo: CashMonthQueryVo, options: any = {}): FetchArgs {
            // verify required parameter 'queryVo' is not null or undefined
            if (queryVo === null || queryVo === undefined) {
                throw new RequiredError('queryVo','Required parameter queryVo was null or undefined when calling cashDateDetail.');
            }
            const localVarPath = `/cash/month`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashMonthQueryVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(queryVo || {}) : (queryVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询年月的资金明细汇总列表
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateList(queryVo: CashMonthQueryVo, options: any = {}): FetchArgs {
            // verify required parameter 'queryVo' is not null or undefined
            if (queryVo === null || queryVo === undefined) {
                throw new RequiredError('queryVo','Required parameter queryVo was null or undefined when calling cashDateList.');
            }
            const localVarPath = `/cash/month/list`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashMonthQueryVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(queryVo || {}) : (queryVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 企业账本参数列表查看
         * @param {number} paramType 参数类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashParamList(paramType: number, options: any = {}): FetchArgs {
            // verify required parameter 'paramType' is not null or undefined
            if (paramType === null || paramType === undefined) {
                throw new RequiredError('paramType','Required parameter paramType was null or undefined when calling cashParamList.');
            }
            const localVarPath = `/cash/param/{paramType}/list`
                .replace(`{${"paramType"}}`, encodeURIComponent(String(paramType)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 资金明细列表
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordList(cashRecordQueryVo: CashRecordQueryVo, options: any = {}): FetchArgs {
            // verify required parameter 'cashRecordQueryVo' is not null or undefined
            if (cashRecordQueryVo === null || cashRecordQueryVo === undefined) {
                throw new RequiredError('cashRecordQueryVo','Required parameter cashRecordQueryVo was null or undefined when calling cashRecordList.');
            }
            const localVarPath = `/cash/record/list`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashRecordQueryVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashRecordQueryVo || {}) : (cashRecordQueryVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 资金明细列表导出
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordListExport(cashRecordQueryVo: CashRecordQueryVo, options: any = {}): FetchArgs {
            // verify required parameter 'cashRecordQueryVo' is not null or undefined
            if (cashRecordQueryVo === null || cashRecordQueryVo === undefined) {
                throw new RequiredError('cashRecordQueryVo','Required parameter cashRecordQueryVo was null or undefined when calling cashRecordListExport.');
            }
            const localVarPath = `/cash/record/export`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashRecordQueryVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashRecordQueryVo || {}) : (cashRecordQueryVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashParam(cashParamVo: CashParam, options: any = {}): FetchArgs {
            // verify required parameter 'cashParamVo' is not null or undefined
            if (cashParamVo === null || cashParamVo === undefined) {
                throw new RequiredError('cashParamVo','Required parameter cashParamVo was null or undefined when calling createCashParam.');
            }
            const localVarPath = `/cash/param`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashParam" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashParamVo || {}) : (cashParamVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 资金明细添加
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashRecord(cashRecord: CashRecord, options: any = {}): FetchArgs {
            // verify required parameter 'cashRecord' is not null or undefined
            if (cashRecord === null || cashRecord === undefined) {
                throw new RequiredError('cashRecord','Required parameter cashRecord was null or undefined when calling createCashRecord.');
            }
            const localVarPath = `/cash/record`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashRecord" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashRecord || {}) : (cashRecord || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {number} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashAccount(accountId: number, options: any = {}): FetchArgs {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling deleteCashAccount.');
            }
            const localVarPath = `/assets/account/{accountId}`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashParam(cashParamVo: CashParam, options: any = {}): FetchArgs {
            // verify required parameter 'cashParamVo' is not null or undefined
            if (cashParamVo === null || cashParamVo === undefined) {
                throw new RequiredError('cashParamVo','Required parameter cashParamVo was null or undefined when calling deleteCashParam.');
            }
            const localVarPath = `/cash/param`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashParam" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashParamVo || {}) : (cashParamVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 资金明细删除
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashRecord(cashRecord: CashRecord, options: any = {}): FetchArgs {
            // verify required parameter 'cashRecord' is not null or undefined
            if (cashRecord === null || cashRecord === undefined) {
                throw new RequiredError('cashRecord','Required parameter cashRecord was null or undefined when calling deleteCashRecord.');
            }
            const localVarPath = `/cash/record`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashRecord" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashRecord || {}) : (cashRecord || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 下载流水导入模版
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCashTemplate(options: any = {}): FetchArgs {
            const localVarPath = `/cash/record/downloadTemplate`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 导入流水
         * @summary 导入流水
         * @param {any} excelFile import cash records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importCashRecords(excelFile: any, options: any = {}): FetchArgs {
            // verify required parameter 'excelFile' is not null or undefined
            if (excelFile === null || excelFile === undefined) {
                throw new RequiredError('excelFile','Required parameter excelFile was null or undefined when calling importCashRecords.');
            }
            const localVarPath = `/cash/record/import`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new url.URLSearchParams();

            if (excelFile !== undefined) {
                localVarFormParams.set('excelFile', excelFile as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询某个账户的详情以及部分流水
         * @param {number} accountId 账户Id
         * @param {number} [pageSize] 每页的账户流水条数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAccountDetail(accountId: number, pageSize?: number, options: any = {}): FetchArgs {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling queryAccountDetail.');
            }
            const localVarPath = `/assets/account/{accountId}/detail`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询所有账户的详情，用于资产管家首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAllAccountsDetail(options: any = {}): FetchArgs {
            const localVarPath = `/assets/accounts/detail`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页查询某个账户的部分流水，根据入参里的lastRecord.seqId进行查询
         * @param {number} accountId 账户Id
         * @param {AssetsAccountDailyFlowQueryVo} queryVo 分页查询的参数，当查询下一页的时候，需要把上一次请求的最后一条流水上传
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryCashFlow(accountId: number, queryVo: AssetsAccountDailyFlowQueryVo, options: any = {}): FetchArgs {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling queryCashFlow.');
            }
            // verify required parameter 'queryVo' is not null or undefined
            if (queryVo === null || queryVo === undefined) {
                throw new RequiredError('queryVo','Required parameter queryVo was null or undefined when calling queryCashFlow.');
            }
            const localVarPath = `/assets/account/{accountId}/cashflow`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"AssetsAccountDailyFlowQueryVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(queryVo || {}) : (queryVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveCashAccount(cashAccountVo: CashAccountVo, options: any = {}): FetchArgs {
            // verify required parameter 'cashAccountVo' is not null or undefined
            if (cashAccountVo === null || cashAccountVo === undefined) {
                throw new RequiredError('cashAccountVo','Required parameter cashAccountVo was null or undefined when calling saveCashAccount.');
            }
            const localVarPath = `/assets/account/save`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashAccountVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashAccountVo || {}) : (cashAccountVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分类打星标
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagStarTarget(cashParamVo: CashParam, options: any = {}): FetchArgs {
            // verify required parameter 'cashParamVo' is not null or undefined
            if (cashParamVo === null || cashParamVo === undefined) {
                throw new RequiredError('cashParamVo','Required parameter cashParamVo was null or undefined when calling tagStarTarget.');
            }
            const localVarPath = `/cash/param/tag/star`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashParam" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashParamVo || {}) : (cashParamVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新企业资产账户余额
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashAccountBalance(cashAccountVo: CashAccountVo, options: any = {}): FetchArgs {
            // verify required parameter 'cashAccountVo' is not null or undefined
            if (cashAccountVo === null || cashAccountVo === undefined) {
                throw new RequiredError('cashAccountVo','Required parameter cashAccountVo was null or undefined when calling updateCashAccountBalance.');
            }
            const localVarPath = `/assets/account/balance/update`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashAccountVo" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashAccountVo || {}) : (cashAccountVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashParam(cashParamVo: CashParam, options: any = {}): FetchArgs {
            // verify required parameter 'cashParamVo' is not null or undefined
            if (cashParamVo === null || cashParamVo === undefined) {
                throw new RequiredError('cashParamVo','Required parameter cashParamVo was null or undefined when calling updateCashParam.');
            }
            const localVarPath = `/cash/param`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashParam" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashParamVo || {}) : (cashParamVo || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 资金明细修改
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashRecord(cashRecord: CashRecord, options: any = {}): FetchArgs {
            // verify required parameter 'cashRecord' is not null or undefined
            if (cashRecord === null || cashRecord === undefined) {
                throw new RequiredError('cashRecord','Required parameter cashRecord was null or undefined when calling updateCashRecord.');
            }
            const localVarPath = `/cash/record`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CashRecord" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(cashRecord || {}) : (cashRecord || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CashFlowApi - functional programming interface
 * @export
 */
export const CashFlowApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 查询指定年月的资金明细汇总
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateDetail(queryVo: CashMonthQueryVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CashMonthVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).cashDateDetail(queryVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 查询年月的资金明细汇总列表
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateList(queryVo: CashMonthQueryVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CashMonthListVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).cashDateList(queryVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 企业账本参数列表查看
         * @param {number} paramType 参数类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashParamList(paramType: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<CashParam>> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).cashParamList(paramType, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 资金明细列表
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordList(cashRecordQueryVo: CashRecordQueryVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<CashRecordDayVo>> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).cashRecordList(cashRecordQueryVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 资金明细列表导出
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordListExport(cashRecordQueryVo: CashRecordQueryVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).cashRecordListExport(cashRecordQueryVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashParam(cashParamVo: CashParam, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).createCashParam(cashParamVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 资金明细添加
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashRecord(cashRecord: CashRecord, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).createCashRecord(cashRecord, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {number} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashAccount(accountId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<boolean> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).deleteCashAccount(accountId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashParam(cashParamVo: CashParam, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).deleteCashParam(cashParamVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 资金明细删除
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashRecord(cashRecord: CashRecord, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).deleteCashRecord(cashRecord, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 下载流水导入模版
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCashTemplate(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).downloadCashTemplate(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 导入流水
         * @summary 导入流水
         * @param {any} excelFile import cash records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importCashRecords(excelFile: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<ExcelImportResultVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).importCashRecords(excelFile, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 查询某个账户的详情以及部分流水
         * @param {number} accountId 账户Id
         * @param {number} [pageSize] 每页的账户流水条数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAccountDetail(accountId: number, pageSize?: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AssetsAccountOverviewVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).queryAccountDetail(accountId, pageSize, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 查询所有账户的详情，用于资产管家首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAllAccountsDetail(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AssetsManagerOverviewVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).queryAllAccountsDetail(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 分页查询某个账户的部分流水，根据入参里的lastRecord.seqId进行查询
         * @param {number} accountId 账户Id
         * @param {AssetsAccountDailyFlowQueryVo} queryVo 分页查询的参数，当查询下一页的时候，需要把上一次请求的最后一条流水上传
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryCashFlow(accountId: number, queryVo: AssetsAccountDailyFlowQueryVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AssetsAccountDailyFlowPagingVo> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).queryCashFlow(accountId, queryVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveCashAccount(cashAccountVo: CashAccountVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).saveCashAccount(cashAccountVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 分类打星标
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagStarTarget(cashParamVo: CashParam, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).tagStarTarget(cashParamVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 更新企业资产账户余额
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashAccountBalance(cashAccountVo: CashAccountVo, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<boolean> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).updateCashAccountBalance(cashAccountVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashParam(cashParamVo: CashParam, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).updateCashParam(cashParamVo, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary 资金明细修改
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashRecord(cashRecord: CashRecord, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = CashFlowApiFetchParamCreator(configuration).updateCashRecord(cashRecord, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * CashFlowApi - factory interface
 * @export
 */
export const CashFlowApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary 查询指定年月的资金明细汇总
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateDetail(queryVo: CashMonthQueryVo, options?: any) {
            return CashFlowApiFp(configuration).cashDateDetail(queryVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 查询年月的资金明细汇总列表
         * @param {CashMonthQueryVo} queryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashDateList(queryVo: CashMonthQueryVo, options?: any) {
            return CashFlowApiFp(configuration).cashDateList(queryVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 企业账本参数列表查看
         * @param {number} paramType 参数类型
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashParamList(paramType: number, options?: any) {
            return CashFlowApiFp(configuration).cashParamList(paramType, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 资金明细列表
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordList(cashRecordQueryVo: CashRecordQueryVo, options?: any) {
            return CashFlowApiFp(configuration).cashRecordList(cashRecordQueryVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 资金明细列表导出
         * @param {CashRecordQueryVo} cashRecordQueryVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashRecordListExport(cashRecordQueryVo: CashRecordQueryVo, options?: any) {
            return CashFlowApiFp(configuration).cashRecordListExport(cashRecordQueryVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashParam(cashParamVo: CashParam, options?: any) {
            return CashFlowApiFp(configuration).createCashParam(cashParamVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 资金明细添加
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCashRecord(cashRecord: CashRecord, options?: any) {
            return CashFlowApiFp(configuration).createCashRecord(cashRecord, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {number} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashAccount(accountId: number, options?: any) {
            return CashFlowApiFp(configuration).deleteCashAccount(accountId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashParam(cashParamVo: CashParam, options?: any) {
            return CashFlowApiFp(configuration).deleteCashParam(cashParamVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 资金明细删除
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCashRecord(cashRecord: CashRecord, options?: any) {
            return CashFlowApiFp(configuration).deleteCashRecord(cashRecord, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 下载流水导入模版
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCashTemplate(options?: any) {
            return CashFlowApiFp(configuration).downloadCashTemplate(options)(fetch, basePath);
        },
        /**
         * 导入流水
         * @summary 导入流水
         * @param {any} excelFile import cash records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importCashRecords(excelFile: any, options?: any) {
            return CashFlowApiFp(configuration).importCashRecords(excelFile, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 查询某个账户的详情以及部分流水
         * @param {number} accountId 账户Id
         * @param {number} [pageSize] 每页的账户流水条数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAccountDetail(accountId: number, pageSize?: number, options?: any) {
            return CashFlowApiFp(configuration).queryAccountDetail(accountId, pageSize, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 查询所有账户的详情，用于资产管家首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryAllAccountsDetail(options?: any) {
            return CashFlowApiFp(configuration).queryAllAccountsDetail(options)(fetch, basePath);
        },
        /**
         * 
         * @summary 分页查询某个账户的部分流水，根据入参里的lastRecord.seqId进行查询
         * @param {number} accountId 账户Id
         * @param {AssetsAccountDailyFlowQueryVo} queryVo 分页查询的参数，当查询下一页的时候，需要把上一次请求的最后一条流水上传
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryCashFlow(accountId: number, queryVo: AssetsAccountDailyFlowQueryVo, options?: any) {
            return CashFlowApiFp(configuration).queryCashFlow(accountId, queryVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveCashAccount(cashAccountVo: CashAccountVo, options?: any) {
            return CashFlowApiFp(configuration).saveCashAccount(cashAccountVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 分类打星标
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagStarTarget(cashParamVo: CashParam, options?: any) {
            return CashFlowApiFp(configuration).tagStarTarget(cashParamVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 更新企业资产账户余额
         * @param {CashAccountVo} cashAccountVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashAccountBalance(cashAccountVo: CashAccountVo, options?: any) {
            return CashFlowApiFp(configuration).updateCashAccountBalance(cashAccountVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 企业账本自定义单元、分类新增
         * @param {CashParam} cashParamVo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashParam(cashParamVo: CashParam, options?: any) {
            return CashFlowApiFp(configuration).updateCashParam(cashParamVo, options)(fetch, basePath);
        },
        /**
         * 
         * @summary 资金明细修改
         * @param {CashRecord} cashRecord 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCashRecord(cashRecord: CashRecord, options?: any) {
            return CashFlowApiFp(configuration).updateCashRecord(cashRecord, options)(fetch, basePath);
        },
    };
};

/**
 * CashFlowApi - object-oriented interface
 * @export
 * @class CashFlowApi
 * @extends {BaseAPI}
 */
export class CashFlowApi extends BaseAPI {
    /**
     * 
     * @summary 查询指定年月的资金明细汇总
     * @param {CashMonthQueryVo} queryVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public cashDateDetail(queryVo: CashMonthQueryVo, options?: any) {
        return CashFlowApiFp(this.configuration).cashDateDetail(queryVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 查询年月的资金明细汇总列表
     * @param {CashMonthQueryVo} queryVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public cashDateList(queryVo: CashMonthQueryVo, options?: any) {
        return CashFlowApiFp(this.configuration).cashDateList(queryVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 企业账本参数列表查看
     * @param {number} paramType 参数类型
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public cashParamList(paramType: number, options?: any) {
        return CashFlowApiFp(this.configuration).cashParamList(paramType, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 资金明细列表
     * @param {CashRecordQueryVo} cashRecordQueryVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public cashRecordList(cashRecordQueryVo: CashRecordQueryVo, options?: any) {
        return CashFlowApiFp(this.configuration).cashRecordList(cashRecordQueryVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 资金明细列表导出
     * @param {CashRecordQueryVo} cashRecordQueryVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public cashRecordListExport(cashRecordQueryVo: CashRecordQueryVo, options?: any) {
        return CashFlowApiFp(this.configuration).cashRecordListExport(cashRecordQueryVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 企业账本自定义单元、分类新增
     * @param {CashParam} cashParamVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public createCashParam(cashParamVo: CashParam, options?: any) {
        return CashFlowApiFp(this.configuration).createCashParam(cashParamVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 资金明细添加
     * @param {CashRecord} cashRecord 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public createCashRecord(cashRecord: CashRecord, options?: any) {
        return CashFlowApiFp(this.configuration).createCashRecord(cashRecord, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
     * @param {number} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public deleteCashAccount(accountId: number, options?: any) {
        return CashFlowApiFp(this.configuration).deleteCashAccount(accountId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 企业账本自定义单元、分类新增
     * @param {CashParam} cashParamVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public deleteCashParam(cashParamVo: CashParam, options?: any) {
        return CashFlowApiFp(this.configuration).deleteCashParam(cashParamVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 资金明细删除
     * @param {CashRecord} cashRecord 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public deleteCashRecord(cashRecord: CashRecord, options?: any) {
        return CashFlowApiFp(this.configuration).deleteCashRecord(cashRecord, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 下载流水导入模版
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public downloadCashTemplate(options?: any) {
        return CashFlowApiFp(this.configuration).downloadCashTemplate(options)(this.fetch, this.basePath);
    }

    /**
     * 导入流水
     * @summary 导入流水
     * @param {any} excelFile import cash records
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public importCashRecords(excelFile: any, options?: any) {
        return CashFlowApiFp(this.configuration).importCashRecords(excelFile, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 查询某个账户的详情以及部分流水
     * @param {number} accountId 账户Id
     * @param {number} [pageSize] 每页的账户流水条数
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public queryAccountDetail(accountId: number, pageSize?: number, options?: any) {
        return CashFlowApiFp(this.configuration).queryAccountDetail(accountId, pageSize, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 查询所有账户的详情，用于资产管家首页
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public queryAllAccountsDetail(options?: any) {
        return CashFlowApiFp(this.configuration).queryAllAccountsDetail(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 分页查询某个账户的部分流水，根据入参里的lastRecord.seqId进行查询
     * @param {number} accountId 账户Id
     * @param {AssetsAccountDailyFlowQueryVo} queryVo 分页查询的参数，当查询下一页的时候，需要把上一次请求的最后一条流水上传
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public queryCashFlow(accountId: number, queryVo: AssetsAccountDailyFlowQueryVo, options?: any) {
        return CashFlowApiFp(this.configuration).queryCashFlow(accountId, queryVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 保存账户，如果Id不传为新增；Id传了则根据Id进行更新操作
     * @param {CashAccountVo} cashAccountVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public saveCashAccount(cashAccountVo: CashAccountVo, options?: any) {
        return CashFlowApiFp(this.configuration).saveCashAccount(cashAccountVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 分类打星标
     * @param {CashParam} cashParamVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public tagStarTarget(cashParamVo: CashParam, options?: any) {
        return CashFlowApiFp(this.configuration).tagStarTarget(cashParamVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 更新企业资产账户余额
     * @param {CashAccountVo} cashAccountVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public updateCashAccountBalance(cashAccountVo: CashAccountVo, options?: any) {
        return CashFlowApiFp(this.configuration).updateCashAccountBalance(cashAccountVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 企业账本自定义单元、分类新增
     * @param {CashParam} cashParamVo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public updateCashParam(cashParamVo: CashParam, options?: any) {
        return CashFlowApiFp(this.configuration).updateCashParam(cashParamVo, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary 资金明细修改
     * @param {CashRecord} cashRecord 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashFlowApi
     */
    public updateCashRecord(cashRecord: CashRecord, options?: any) {
        return CashFlowApiFp(this.configuration).updateCashRecord(cashRecord, options)(this.fetch, this.basePath);
    }

}

