// tslint:disable
/**
 * es-cash-flow-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashRecord
 */
export interface CashRecord {
    /**
     * 明细id
     * @type {number}
     * @memberof CashRecord
     */
    id?: number;
    /**
     * 现金流向类别，1:支出 2:收入
     * @type {number}
     * @memberof CashRecord
     */
    direction?: number;
    /**
     * 账户id
     * @type {number}
     * @memberof CashRecord
     */
    accountId?: number;
    /**
     * 类别id
     * @type {number}
     * @memberof CashRecord
     */
    tag?: number;
    /**
     * 金额
     * @type {number}
     * @memberof CashRecord
     */
    amount?: number;
    /**
     * 费用发生日期
     * @type {Date}
     * @memberof CashRecord
     */
    cashDate?: Date;
    /**
     * 备注
     * @type {string}
     * @memberof CashRecord
     */
    remark?: string;
}

export function CashRecordFromJSON(json: any): CashRecord {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'cashDate': !exists(json, 'cashDate') ? undefined : new Date(json['cashDate']),
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
    };
}

export function CashRecordToJSON(value?: CashRecord): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'direction': value.direction,
        'accountId': value.accountId,
        'tag': value.tag,
        'amount': value.amount,
        'cashDate': value.cashDate === undefined ? undefined : value.cashDate.toISOString(),
        'remark': value.remark,
    };
}


